// Generated by CoffeeScript 1.3.3
(function() {
  var App, Member, jane;

  App = Em.Application.create();

  App.MyView = Em.View.extend({
    mouseDown: function() {
      return window.alert("hello world!");
    }
  });

  Member = Em.Object.extend({
    say: function(thing) {
      return alert(thing);
    }
  });

  jane = Member.create({
    name: "Jane Kim",
    year: "CC'14",
    helloWorld: function() {
      return this.say("hello world, I'm " + this.get('name'));
    }
  });

  jane.helloWorld();

}).call(this);
